# Generated by Django 5.1.3 on 2024-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeinject',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
