# Generated by Django 5.1.3 on 2024-11-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0002_codeinject_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeinject',
            old_name='text',
            new_name='cpp',
        ),
    ]
