# Generated by Django 5.1.3 on 2024-11-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0005_alter_codeinject_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeinject',
            name='cpp',
            field=models.TextField(blank=True, max_length=13000, null=True, verbose_name='C++ Code'),
        ),
        migrations.AlterField(
            model_name='codeinject',
            name='py',
            field=models.TextField(blank=True, max_length=13000, null=True, verbose_name='Python Code'),
        ),
        migrations.AlterField(
            model_name='codeinject',
            name='title',
            field=models.TextField(max_length=130, verbose_name='Title'),
        ),
    ]
